[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
hello-world = "36PZyf6LkXskmMPritchVQc4YF2B21w6geGTwp2Yk88M"
hello-world-extended = "EAMLr7xgt3SLpuybeGzU46AcaPXyZgvSGQ7oHaZR24MF"

[programs.localnet]
hello-world = "36PZyf6LkXskmMPritchVQc4YF2B21w6geGTwp2Yk88M"
hello-world-extended = "EAMLr7xgt3SLpuybeGzU46AcaPXyZgvSGQ7oHaZR24MF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sahil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/helloWorldExtended/helloWorldExtended.test.ts"
