[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
hello-world = "CFcEae71dUQ8sbhu7U7h4gJSAuqGUiQ3xSqDNLCk44J"
hello-world-extended = "GupvfozWTiXJ27WQYK1L9KwWCq6bSbDy4DxqgdKurGkN"

[programs.localnet]
hello-world = "CFcEae71dUQ8sbhu7U7h4gJSAuqGUiQ3xSqDNLCk44J"
hello-world-extended = "GupvfozWTiXJ27WQYK1L9KwWCq6bSbDy4DxqgdKurGkN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sahil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/helloWorldExtended/helloWorldExtended.test.ts"
