[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello-world = "GkUVBKTUKJ5Ab31fVbFtXwpXBuSmyQBNUCJWAbgherws"
hello-world-extended = "2jSp5Yi6LjGN55tN1kdVKDkLJbo8moCHWkqhRekdJ4er"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sahil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
