name: Squads Program Upgrade (Devnet)

on:
  workflow_dispatch:
    inputs:
      network-url:
        description: "Solana network URL"
        required: true
        default: "https://api.devnet.solana.com"
      multisig-pda:
        description: "Multisig PDA address"
        required: true
      multisig-vault-index:
        description: "The multisig vault index"
        required: true
        default: "0"
      program-id:
        description: "Program ID"
        required: true
      buffer:
        description: "Buffer address"
        required: true
      spill-address:
        description: "Spill address"
        required: true
      name:
        description: "Upgrade name"
        required: false
        default: "Devnet Upgrade Test"
      executable-data:
        description: "Executable data address"
        required: true
      idl-buffer:
        description: "The new idl buffer"
        required: false

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install latest Yarn
        run: corepack prepare yarn@stable --activate
      
      - name: Install dependencies
        run: yarn install

      - name: Run program upgrade script
        env:
          NETWORK_URL: ${{ inputs.network-url }}
          MULTISIG_PDA: ${{ inputs.multisig-pda }}
          MULTISIG_VAULT_INDEX: ${{ inputs.multisig-vault-index }}
          PROGRAM_ID: ${{ inputs.program-id }}
          BUFFER: ${{ inputs.buffer }}
          SPILL_ADDRESS: ${{ inputs.spill-address }}
          NAME: ${{ inputs.name }}
          KEYPAIR: ${{ inputs.keypair }}
          EXECUTABLE_DATA: ${{ inputs.executable-data }}
          IDL_BUFFER: ${{ inputs.idl-buffer }}
        run: npx tsx src/main.ts
