name: Squads Program Upgrade (Devnet)

on:
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Squads V4 program upgrade action
        uses: Squads-Protocol/squads-v4-program-upgrade
        with:
          network-url: "https://api.devnet.solana.com"
          multisig-pda: "7q23jbHXV7zURNJkx6ybq7SCcaFMdYG5JWZbD5QDTbNf"
          multisig-vault-index: "0"
          program-id: "CFcEae71dUQ8sbhu7U7h4gJSAuqGUiQ3xSqDNLCk44J"
          buffer: "B91pUKNcx5AHrfiNDbSQ95Vbp3mAS7ooz8QGqCPMp5qT"
          spill-address: "7xBuZLi5B9V55L3Q9AWYHc9iKFZYjZhxhY6YLnrZ5Vy3"
          name: "Devnet Upgrade Test"
          executable-data: "3eAi3uw9oUEfkhRHg9NK8kB1Fu5guVs2boirMFCmVV6P"
          keypair: ${{ secrets.USER_KEYPAIR }}
