name: Squads Program Upgrade (Devnet)

on:
  workflow_dispatch:
    inputs:
      network-url:
        description: "Solana network URL"
        required: true
        default: "https://api.devnet.solana.com"
      multisig-pda:
        description: "Multisig PDA address"
        required: true
      multisig-vault-index:
        description: "The multisig vault index"
        required: true
        default: "0"
      program-id:
        description: "Program ID"
        required: true
      buffer:
        description: "Buffer address"
        required: true
      spill-address:
        description: "Spill address"
        required: true
      name:
        description: "Upgrade name"
        required: false
        default: "Devnet Upgrade Test"
      executable-data:
        description: "Executable data address"
        required: true

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Squads V4 program upgrade action
        uses: Squads-Protocol/squads-v4-program-upgrade@beta
        with:
          network-url: ${{ inputs.network-url }}
          multisig-pda: ${{ inputs.multisig-pda }}
          multisig-vault-index: ${{ inputs.multisig-vault-index }}
          program-id: ${{ inputs.program-id }}
          buffer: ${{ inputs.buffer }}
          spill-address: ${{ inputs.spill-address }}
          name: ${{ inputs.name }}
          executable-data: ${{ inputs.executable-data }}
          keypair: ${{ secrets.USER_KEYPAIR }}
